TEAM_PROJECT/TEAM_PROJECT/Controllers/PersonalTableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TEAM_PROJECT.DB;
using System.Collections.Generic;
using System.Collections;
using System.Net;
using Newtonsoft.Json;
using TEAM_PROJECT.Models;
namespace TEAM_PROJECT.Controllers
{
    public class PersonalTableController : Controller
    {
        public static int Row;
        public static int Column;
        public ActionResult Index()
        {
            Repository repo = new Repository();
            ViewBag.CellList = repo.Get();
            ViewBag.RowsCount = repo.GetRowsAmount();

            return View("~/Views/PersonalTable/Index.cshtml");
        }
        public ActionResult Method(string value)
        {
            PersonalTable pt = new PersonalTable(value);
            Repository repo = new Repository();
            repo.AddItem(pt);

            ViewBag.CellList = repo.Get();
            ViewBag.RowsCount = repo.GetRowsAmount();
            return View("~/Views/PersonalTable/Index.cshtml");
        }
        public ActionResult ViewPage(int row, int column)
        {
            Repository repo = new Repository();
            Row = row;
            Column = column;
            return View("~/Views/PersonalTable/View.cshtml");
        }
        public ActionResult Upgrade(string value)
        {
            Repository repo = new Repository();
            repo.ChangeItemEnd(value, Row, Column);
            ViewBag.CellList = repo.Get();
            ViewBag.RowsCount = repo.GetRowsAmount();
            return View("~/Views/PersonalTable/Index.cshtml");

        }
        public ActionResult Delete()
        {
            Repository repo = new Repository();
            repo.DeleteItemEnd(Row, Column);
            ViewBag.CellList = repo.Get();
            ViewBag.RowsCount = repo.GetRowsAmount();
            return View("~/Views/PersonalTable/Index.cshtml");
        }
        public ActionResult ClearTable()
        {
            Repository repo = new Repository();
            repo.ClearData();
            ViewBag.CellList = repo.Get();
            ViewBag.RowsCount = repo.GetRowsAmount();
            return View("~/Views/PersonalTable/Index.cshtml");

        }
    }
}

TEAM_PROJECT/TEAM_PROJECT/Views/PersonalTable/Index.cshtml
@model TEAM_PROJECT.Models.PersonalTable

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    a {
        color: white;
        cursor: default;
    }

    h3 {
        font-size: 15px;
        color: #fff;
        text-transform: uppercase;
        font-weight: 300;
        text-align: center;
        margin-bottom: 15px;
        cursor: default;
    }
</style>

<section>
    <!--for demo wrap-->
    <h1>TABLE</h1>
    <div class="tbl-header">
        <div class="tbl-content">
            <table cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    @{
                        for (int i = 0; i < ViewBag.RowsCount; i++)
                        {
                            <tr>
                                @{
                                    foreach (var item in ViewBag.CellList)
                                    {
                                        if (item.id_row == i)
                                        {
                                            <td>
                                                <a onclick="location.href='@Url.Action("ViewPage", "PersonalTable", new { row = i, column = item.id_column })'" class="button button-green">@item.value</a>
                                            </td>
                                        }
                                    }
                                }
                            </tr>
                                    }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <h3 onclick="location.href='@Url.Action("ClearTable", "PersonalTable", null)'">Очистить таблицу</h3>
</section>

TEAM_PROJECT/TEAM_PROJECT/Views/PersonalTable/View.cshtml
@model TEAM_PROJECT.Models.PersonalTable

@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    a {
        color: white;
    }
</style>

<section>
    <!--for demo wrap-->
    <h1>TABLE</h1>
    <div class="tbl-header">

        <table cellpadding="0" cellspacing="0" border="0">
            <thead>
                <tr>
                    <th>
                        <h4 class="button button-green">Изменение значения</h4>
                        @using (Html.BeginForm("Upgrade", "PersonalTable", "POST"))
                        {
                            @Html.EditorFor(model => model.Value)
                            <input type="submit" value="Изменить" />
                        }
                    </th>
                </tr>
            </thead>
        </table>

        <table cellpadding="0" cellspacing="0" border="0">
            <thead>
                <tr>
                    <th>
                        <h4 class="button button-green">Удаление значения</h4>
                        @using (Html.BeginForm("Delete", "PersonalTable", "POST"))
                        {
                            <input type="submit" value="Удалить" />
                        }
                    </th>
                </tr>
            </thead>
        </table>

    </div>

</section>